### ISSUE TITLE
我替换了一个默认的工作流，为啥生出来的都是sfw图，都很正常，这个不是涩图吗

### ISSUE THREAD

**Issue by dannyliuuu** [dannyliuuu/Easy_AI_Hentai#1]

**Comment by dannyliuuu** [comment]
不好意思，我发现我测试的时候把涩涩部分注释掉了，你可以把main.py的102到122行的井号删除来取消注释，再试试

**Comment by asdsame** [comment]
更新后解决了，但是又发现了个问题，您的example.yml的#工作流路径默认是workflow_templates\1lora_hyper_sdxl.json，并不是0lora，改了0lora的ckpt名字之后运行main.py会报错。
其次生出来的图，默认没有负面，不知道为啥

**Comment by dannyliuuu** [comment]
> 更新后解决了，但是又发现了个问题，您的example.yml的#工作流路径默认是workflow_templates\1lora_hyper_sdxl.json，并不是0lora，改了0lora的ckpt名字之后运行main.py会报错。 其次生出来的图，默认没有负面，不知道为啥

是的是的，发现了，下午刚刚改的，没检查好。现在
- 默认的工作流改成0lora了。
- 负面tag应该可以正常配置了。
- “改了0lora的ckpt名字之后运行main.py会报错”，这个是什么错误呢？我自己测试没发现有错误
你现在再试试看？

**Comment by asdsame** [comment]
其实是同一个错误，就是默认工作流的问题。1lora_hyper_sdxl.json我没改ckpt名字，运行就会报错。
我还没试，不过应该问题不大了。
谢谢lz的脚本

**Comment by dannyliuuu** [comment]
@asdsame 不客气，有 改进意见/想要加入的新姿势 请尽管提。

**Comment by asdsame** [comment]
@dannyliuuu 我在看tg群有的comfyui佬批量设置的文件夹图片sd反推，配合上tag通配符，其实也能随机出瑟图，前期工作就是搜集各种瑟图，就是各种节点门槛有点复杂，不知道脚本可以实现不

**Comment by dannyliuuu** [comment]
> @dannyliuuu 我在看tg群有的comfyui佬批量设置的文件夹图片sd反推，配合上tag通配符，其实也能随机出瑟图，前期工作就是搜集各种瑟图，就是各种节点门槛有点复杂，不知道脚本可以实现不

我没见过你说的节点，不知道有多复杂。脚本肯定是能做的（因为脚本调用的就是工作流，只是修改工作流的参数而已），不过既然工作流已经能用了，其实没必要再用脚本。

我最开始写这个项目的时候也以为随机出图是重点，不过写着写着就发现其实纯随机不是很有意思：
- 一般来说角色、衣装、所处环境不能随机，一方面这个是由赞助者投票选择的，我们要保留人工控制的能力；另一方面，我看色图看的就是自己熟悉的角色，随便乱roll一个角色感觉很难起性欲。
- 至于姿势倒是可以随机，但也必须是几个tag同时使用，比如 吮吸手指 这个姿势，只写licking_finger就很难出图，要把 licking_finger, finger_sucking,  (finger_in_another's_mouth:1.4), upper body, looking at viewer, pov,  pov hands, hand on another's cheek, (solo focus:1.3) 一起写上，出图才稳定。所以我这里的随机不是以tag为单位进行的，而是以tag组为单位进行的。

所以，确实和tag通配符没有什么本质区别，我觉得这个项目的优点就是我自己用着顺手，因为我不想用太多的节点连连看。另一个有价值的部分就是我自己整理的tags/sex.yml, 这里面的组合我觉得出图率还行。

另外，你提到的 “前期工作就是搜集各种瑟图” ，如果要追求标签丰富度的话，我认为有另一种类似但更加快速的做法：Danbooru上的图片是有标签的，可以直接下载2023年全年的danbooru图片的标签（注意是标签而不是原图），压缩包2.81G，然后把所有带有sex关键字的筛出来就行了。标签是json文件，很好处理。这种方法是利用danbooru上人工标注的标签，而不是反推出来的，而且就算是2023年一年的数据也绝对比人工搜集图片要多得多。唯一的缺点是很有可能包括很多不合你性癖的东西（你看，随机性的缺点来了）
链接在这里：https://huggingface.co/datasets/nyanko7/danbooru2023/tree/main/metadata
